name: NuGet Package Generation

on:
  push:
    branches:
      - release
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/victoriaquasar/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
          
      - name: Build solution and generate NuGet package
        run: |  
          cd Cli.NET
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./Cli.NET/out/*.nupkg --skip-duplicate --no-symbols true
